// The social card is a fixed, pre-rendered asset in public/, so it is served
// directly from the static asset host. It is deliberately not generated by a route
// handler: reading it through node:fs has no filesystem to read from on a Workers
// runtime, which returned 500 for every link-preview crawl.
export const socialImageAlt =
  "InnerArc Personal Pattern Intelligence with the number 11 and three abstract reflective card backs";
export const socialImageSize = { width: 1200, height: 630 } as const;
export const socialImageContentType = "image/png";
export const socialImagePath = "/og.png";
