import type { PaidReadingInput, PaidReport } from "@/core/paid-reading";
import type { Locale } from "@/i18n/config";
import { createPaidReport } from "@/server/reports/paid-report";

export const sampleReportKinds = ["detail", "premium", "saju"] as const;
export type SampleReportKind = (typeof sampleReportKinds)[number];

export function isSampleReportKind(value: string): value is SampleReportKind {
  return sampleReportKinds.includes(value as SampleReportKind);
}

/** The one birth date every published sample is calculated from. */
export const SAMPLE_REPORT_BIRTH_DATE = "1994-11-04";

function sampleInput(kind: SampleReportKind, locale: Locale): PaidReadingInput {
  return {
    version: 1,
    locale,
    productCode: kind === "premium" ? "premium_pdf" : kind === "detail" ? "pro_30d" : "plus_30d",
    readingKind: kind === "saju" ? "saju_chart" : "numerology",
    birthDate: SAMPLE_REPORT_BIRTH_DATE,
    name: "",
    focusId: "growth",
    concern: "",
    gender: "female",
    midnightConvention: "야자시",
    createdAt: "2026-08-21T00:00:00.000Z",
  };
}

const cache = new Map<string, PaidReport>();

/**
 * The published sample report, generated by the production generator.
 *
 * The `/samples` pages and the home report preview both read this, so what a visitor is
 * shown before paying and what the sample page renders cannot drift apart. The input is
 * fixed, and the generators are deterministic, so the result is cached per kind and
 * locale rather than recomputed on every render of a `force-dynamic` page.
 */
export function getSampleReport(kind: SampleReportKind, locale: Locale): PaidReport {
  const key = `${kind}:${locale}`;
  const cached = cache.get(key);
  if (cached) return cached;
  const report = createPaidReport(`sample941104${kind}`, sampleInput(kind, locale));
  cache.set(key, report);
  return report;
}
