import { DreamSourceSchema, type DreamSource } from "./schema";

const catalog: DreamSource[] = [
  {
    sourceId: "dream-source:artemidorus-oneirocritica",
    title: "Oneirocritica",
    author: "Artemidorus of Daldis",
    period: "2nd century CE",
    culture: "Graeco-Roman",
    sourceType: "primary_text",
    primaryOrSecondary: "primary",
    academicQuality: "A",
    historicalAuthenticity: "established",
    translationQuality: "scholarly",
    citation: "https://academic.oup.com/book/40085",
    notes: "The only complete surviving Graeco-Roman dream manual; interpretations are contextual to the dreamer's life and circumstances.",
  },
  {
    sourceId: "dream-source:korean-folklore-encyclopedia",
    title: "Encyclopedia of Korean Folk Culture",
    author: "National Folk Museum of Korea",
    period: "Contemporary institutional record of transmitted traditions",
    culture: "Korean",
    sourceType: "museum",
    primaryOrSecondary: "secondary",
    academicQuality: "A",
    historicalAuthenticity: "qualified",
    translationQuality: "institutional",
    citation: "https://folkency.nfm.go.kr/kr/",
    notes: "Institutional reference for Korean folk practices. Entries remain cultural records, not evidence that dreams predict events.",
  },
  {
    sourceId: "dream-source:ancient-chinese-chengwu",
    title: "Of Trees, a Son, and Kingship: Recovering an Ancient Chinese Dream",
    author: "Edward L. Shaughnessy",
    period: "2018 study of a Warring States manuscript tradition",
    culture: "Ancient Chinese",
    sourceType: "peer_reviewed",
    primaryOrSecondary: "secondary",
    academicQuality: "A",
    historicalAuthenticity: "qualified",
    translationQuality: "original_language",
    citation: "https://doi.org/10.1017/S0021911818000517",
    notes: "A philological study of the Tsinghua Cheng Wu manuscript showing that an early dream account has a traceable textual history and that later received interpretations can be disputed.",
  },
  {
    sourceId: "dream-source:brihat-samhita-dreams",
    title: "Brihat Samhita — dream and omen traditions",
    author: "Varahamihira",
    period: "6th century CE",
    culture: "South Asian",
    sourceType: "primary_text",
    primaryOrSecondary: "primary",
    academicQuality: "B",
    historicalAuthenticity: "established",
    translationQuality: "qualified",
    citation: "https://archive.org/details/BrihatSamhita",
    notes: "A historical Sanskrit compendium. Surviving translations vary, so specific claims require edition-level checking.",
  },
  {
    sourceId: "dream-source:islamic-three-dream-types",
    title: "Sahih Muslim, Book of Dreams",
    author: "Muslim ibn al-Hajjaj (compiler)",
    period: "9th century CE compilation",
    culture: "Islamic",
    sourceType: "primary_text",
    primaryOrSecondary: "primary",
    academicQuality: "A",
    historicalAuthenticity: "established",
    translationQuality: "qualified",
    citation: "https://sunnah.com/muslim/42",
    notes: "Used only for the historical distinction among kinds of dreams. Later manuals attributed to Ibn Sirin are not treated as securely authored primary works.",
  },
  {
    sourceId: "dream-source:continuity-schredl-2000",
    title: "Continuity between waking life and dreaming",
    author: "Michael Schredl",
    period: "2000",
    culture: "Modern dream research",
    sourceType: "peer_reviewed",
    primaryOrSecondary: "secondary",
    academicQuality: "A",
    historicalAuthenticity: "not_applicable",
    translationQuality: "original_language",
    citation: "https://journals.sagepub.com/doi/10.2466/pms.2000.90.3.844",
    notes: "Supports cautious comparison between waking concerns and dream content; it does not validate prediction.",
  },
  {
    sourceId: "dream-source:dream-lag-2011",
    title: "Time course of memory incorporation into dreams",
    author: "Blagrove et al.",
    period: "2011",
    culture: "Modern dream research",
    sourceType: "peer_reviewed",
    primaryOrSecondary: "primary",
    academicQuality: "A",
    historicalAuthenticity: "not_applicable",
    translationQuality: "original_language",
    citation: "https://pubmed.ncbi.nlm.nih.gov/22046336/",
    notes: "Small laboratory study reporting immediate and delayed incorporation of waking events; the sample limits generalization.",
  },
  {
    sourceId: "dream-source:early-late-night-2020",
    title: "Dreams reflect nocturnal cognitive processes",
    author: "Malinowski et al.",
    period: "2020",
    culture: "Modern dream research",
    sourceType: "peer_reviewed",
    primaryOrSecondary: "primary",
    academicQuality: "A",
    historicalAuthenticity: "not_applicable",
    translationQuality: "original_language",
    citation: "https://pubmed.ncbi.nlm.nih.gov/33360822/",
    notes: "Finds early-night dreams more continuous with waking life and late-night reports more emotional and associative in a 68-person study.",
  },
  {
    sourceId: "dream-source:aasm-nightmare-position-2018",
    title: "Position Paper for the Treatment of Nightmare Disorder in Adults",
    author: "American Academy of Sleep Medicine",
    period: "2018",
    culture: "Clinical sleep medicine",
    sourceType: "clinical_guideline",
    primaryOrSecondary: "secondary",
    academicQuality: "A",
    historicalAuthenticity: "not_applicable",
    translationQuality: "original_language",
    citation: "https://pmc.ncbi.nlm.nih.gov/articles/PMC5991964/",
    notes: "Clinical safety reference for recurring nightmares. The product does not diagnose nightmare disorder or trauma.",
  },
];

export const DREAM_SOURCE_CATALOG = Object.freeze(catalog.map((source) => DreamSourceSchema.parse(source)));
const byId = new Map(DREAM_SOURCE_CATALOG.map((source) => [source.sourceId, source]));

export function dreamSourcesById(ids: readonly string[]): DreamSource[] {
  return [...new Set(ids)].map((id) => byId.get(id)).filter((value): value is DreamSource => Boolean(value));
}

export function assertAllowlistedDreamSourceIds(ids: readonly string[]): void {
  const unknown = ids.find((id) => !byId.has(id));
  if (unknown) throw new Error(`UNKNOWN_DREAM_SOURCE:${unknown}`);
}
