import { describe, expect, it } from "vitest";
import { manualScene, estimatedMeasurements } from "@/core/space/schema";
import { calibrateScene } from "@/core/space/measurement";
import { analyzeSpace, geometryIssues } from "@/core/space/engine";
import { clearTranslation, spatialAccessIssues } from "@/core/space/navigation";
describe("space measurement provenance", () => {
  it("cannot turn a photo estimate into calibrated geometry by ticking confirmation", () => { const scene = manualScene(); scene.confirmed = scene.orientation.confirmed = true; scene.measurements = estimatedMeasurements("photo", .99); expect(() => analyzeSpace(scene, "rest", "en")).toThrow("REFERENCE_MEASUREMENT_REQUIRED"); });
  it("calibrates proportions, coordinates and openings while confirming only the reference axis", () => { const scene = manualScene(), next = calibrateScene(scene, "width", 6); expect(next.room.width).toBe(6); expect(next.room.depth).toBe(7.5); expect(next.room.height).toBe(2.5); expect(next.objects[0].x).toBe(1.5); expect(next.windows[0].offset).toBe(3); expect(next.measurements?.width.status).toBe("user_corrected"); expect(next.measurements?.depth.status).toBe("estimated"); expect(next.confirmed).toBe(false); expect(geometryIssues(next)).toEqual([]); });
  it("uses the same reference snapshot on repeated calibration, without cumulative scaling", () => { const first = calibrateScene(manualScene(), "width", 6); expect(calibrateScene(first, "width", 6)).toEqual(first); const restored = calibrateScene(first, "width", 4); expect(restored.objects[0].x).toBe(1); expect(restored.room.depth).toBe(5); });
  it("preserves explicitly corrected furniture dimensions and other room measurements", () => { const scene = manualScene(); scene.objects[0].dimensionSource = "user_corrected"; scene.measurements!.depth = { status: "user_corrected", confidence: 1 }; const next = calibrateScene(scene, "width", 6); expect(next.objects[0].width).toBe(1.4); expect(next.room.depth).toBe(5); });
  it("rejects unsupported reference dimensions without clamping", () => { expect(() => calibrateScene(manualScene(), "width", 100)).toThrow(); });
});
describe("continuous movement and bounded walking checks", () => {
  it("detects a thin object between safe endpoints that sample-only animation would miss", () => { const scene = manualScene(); scene.room = { width: 20, depth: 5, height: 2.5 }; scene.objects = [{ ...scene.objects[1], id: "moving", x: 1, z: 3, width: .1, depth: .1 }, { ...scene.objects[1], id: "thin", x: 10.13, z: 3, width: .1, depth: .1 }]; expect(clearTranslation(scene, scene.objects[0], 19, 3)).toBe(false); expect(clearTranslation(scene, scene.objects[0], 3, 3)).toBe(true); });
  it("detects a room divided by dense furniture even when the exit itself is clear", () => { const scene = manualScene(); scene.objects = [{ ...scene.objects[1], id: "barrier", x: 2, z: 2.5, width: 3.9, depth: .4 }, { ...scene.objects[1], id: "beyond", x: 2, z: 1, width: 1, depth: .5 }]; expect(spatialAccessIssues(scene)).toContain("FURNITURE_ROUTE:beyond"); });
  it("distinguishes a low table beneath a measured window from tall obstruction", () => { const scene = manualScene(); scene.windows[0].sill = .9; scene.objects = [{ ...scene.objects[1], x: 2.6, z: .3, height: .75 }]; expect(spatialAccessIssues(scene).some(i => i.includes("WINDOW"))).toBe(false); scene.objects[0].height = 1.6; expect(spatialAccessIssues(scene)).toContain("WINDOW_OBSTRUCTED:window_1"); delete scene.windows[0].sill; expect(spatialAccessIssues(scene)).toContain("MEASURE_WINDOW:window_1"); });
});
